c***********************************************************************
c
c     param.inc
c
c     parameter definitions
c
c     included in:  arcon96, blockdata, init, metread, proc, record,
c                   scenread, shift, summary, xoqcalc5, xoq95
c
c***********************************************************************

      integer maxfiles, maxhours

      parameter  (maxfiles = 10, maxhours = 10000)
